#!/bin/bash

./getopentickets &
./getnewtickets &
./getpendingtickets &
./getonholdtickets &

wait

cat newtickets >> opentickets
cat pendingtickets >> opentickets
cat onholdtickets >> opentickets

./pullSLAs
./pullassignees
