#!/bin/bash

TOKEN=$(cat token)
CREDENTIALS=$(cat creds)
TARGET=$(cat target)

mkdir -p tmpl
rm -rf tmpl/*

function APICALL()
{
        REQUEST=$(curl -s -u $CREDENTIALS/token:$TOKEN "https://$TARGET/api/v2/tickets/${1}.json?include=users,groups" | ruby prettify_json.rb)
    ASSIGNEEID=$(echo "$REQUEST" | egrep -i "assignee_id" | awk {'print $2'} | sed 's/.$//')

    #GET ASSIGNEE
    ASSIGNEE=''
    NAMEIDS=$(echo "$REQUEST" | egrep -i '"id"|"name"')
    ASSIGNEE=$( echo "$NAMEIDS" | awk "/${ASSIGNEEID}/{getline; print}" | awk -F '"' '{print $4}')

    #GET GROUP
    GROUP=$( echo "$REQUEST" | grep -v "url" | grep -A7 groups | grep '"name": ' | awk -F '"' '{print $4}' )

    if [ -z "$ASSIGNEE" ] ; then
        ASSIGNEE="$GROUP"
    fi

        touch $(pwd)/tmpl/${1}
        tmpf=$(pwd)/tmpl/${1}

        echo "${1} ${ASSIGNEE}" > $tmpf
}

for i in $( awk {'print $1'} < SLAtimes.html ) ; do
        APICALL ${i} &
done

wait

cat tmpl/* | awk '{print $0"<br>"}' > assignees.html

touch tmp
while read k; do
        TICKETNUMBER=$(echo "$k" | awk '{print $1}')
        echo "$(cat assignees.html | grep $TICKETNUMBER)" >> tmp
done < SLAtimes.html && mv tmp assignees.html
